/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HrRouteImport } from './routes/hr'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as SelfServiceRouteImport } from './routes/self-service'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfServiceRoute = SelfServiceRouteImport.update({
  id: '/self-service',
  path: '/self-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/documents': typeof DocumentsRoute
  '/hr': typeof HrRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/recruitment': typeof RecruitmentRoute
  '/self-service': typeof SelfServiceRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/documents': typeof DocumentsRoute
  '/hr': typeof HrRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/recruitment': typeof RecruitmentRoute
  '/self-service': typeof SelfServiceRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/documents': typeof DocumentsRoute
  '/hr': typeof HrRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/recruitment': typeof RecruitmentRoute
  '/self-service': typeof SelfServiceRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/documents'
    | '/hr'
    | '/locations'
    | '/payroll'
    | '/performance'
    | '/recruitment'
    | '/self-service'
    | '/settings'
    | '/users'
    | '/employees/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/documents'
    | '/hr'
    | '/locations'
    | '/payroll'
    | '/performance'
    | '/recruitment'
    | '/self-service'
    | '/settings'
    | '/users'
    | '/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attendance'
    | '/documents'
    | '/hr'
    | '/locations'
    | '/payroll'
    | '/performance'
    | '/recruitment'
    | '/self-service'
    | '/settings'
    | '/users'
    | '/employees/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRoute
  DocumentsRoute: typeof DocumentsRoute
  HrRoute: typeof HrRoute
  LocationsRoute: typeof LocationsRoute
  PayrollRoute: typeof PayrollRoute
  PerformanceRoute: typeof PerformanceRoute
  RecruitmentRoute: typeof RecruitmentRoute
  SelfServiceRoute: typeof SelfServiceRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-service': {
      id: '/self-service'
      path: '/self-service'
      fullPath: '/self-service'
      preLoaderRoute: typeof SelfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRoute,
  DocumentsRoute: DocumentsRoute,
  HrRoute: HrRoute,
  LocationsRoute: LocationsRoute,
  PayrollRoute: PayrollRoute,
  PerformanceRoute: PerformanceRoute,
  RecruitmentRoute: RecruitmentRoute,
  SelfServiceRoute: SelfServiceRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
